name: Build and Test
on:
  workflow_call:
    inputs:
      state:
        required: true
        description: "Application build state (staging or production)"
        type: string
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packet
        run: npm ci
      - name: Run test
        run: npm test
        env:
          CI: true
      - name: Generate build staging
        run: npm run build
        env:
          REACT_APP_STAGE: ${{inputs.state}}
      - name: Share artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build-path
          path: |
            build
            .firebaserc
            firebase.json
      - name: Test Failure
        if: ${{ failure() }}
        run: echo "Failure"
      - name: Test Always
        if: ${{ always() }}
        run: echo "Always"
