name: Build application to deploy
on:
  workflow_call:
    inputs:
      state:
        required: true
        description: "Application build state (staging or production)"
        type: string
jobs:
  checkout:
    runs-on: [self-hosted]
    steps:
      - name: Github checkout
        uses: actions/checkout@v3
      - name: Setup Node 14
        uses: actions/setup-node@v3
        with:
          node-verison: "14"
      - run: npm ci && npm run test
        env:
          CI: true
      - run: npm run build
        env:
          REACT_APP_STAGE: ${{inputs.state}}
      - uses: actions/upload-artifact@v3
        with:
          name: application-artiface
          path: |
            build
            .firebaserc
            firebase.json