name: Deploy Cloud Run
on:
  workflow_dispatch:
    inputs:
      state:
        required: true
        type: choice
        description: State
        options:
        - development
        - production
env:
  PROJECT_ID: kslplusstaging
  SERVICE: github_actions
jobs:
  build_and_test:
    uses: ./.github/workflows/build-test.yml
    with:
      state: staging
  deploy_preview_channels:
    runs-on: [self-hosted]
    needs: build_and_test
    steps:
      - name: Load build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build-path
      - id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      # - name: 'Deploy to Cloud Run'
      #   uses: 'google-github-actions/deploy-cloudrun@v0'
      #   with:
      #     image: 'gcr.io/cloudrun/hello'
      #     service: 'hello-cloud-run'
      # - name: Preview URL
      #   run: echo "${{steps.firebase_preview.outputs.details_url}}"
