name: Action on label
on:
  pull_request:
    branches:
      - main
    types:
      - labeled

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      state: staging
  check_label:
    if: github.event.label.name == 'ready to merge'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "${{ toJson(github) }}"
      - name: Step Always
        run: echo "Always"
        if: always()
      - name: Step Failure
        run: echo "Failure"
        if: failure()
  if_error_or_failure:
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    runs-on: ubuntu-latest
    steps:
      - env:
          DESCRIPTION: ${{github.event.description}}
        run: |
          echo The status is error or failed: $DESCRIPTION
  if_success:
    if: github.event.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}"
  if_pending:
    if: github.event.state == 'pending'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}"