name: Action on label
on:
  pull_request:
    branches:
      - main
    types:
      - labeled

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      state: staging
    - name: Test Failure
      if: ${{ failure() }}
      run: echo "Failure"
    - name: Test Always
      if: ${{ always() }}
      run: echo "Always"
  check_label:
    if: github.event.label.name == 'ready to merge'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "${{ toJson(github) }}"
  check_status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Step Always
        run: echo "Always"
        if: always()
      - name: Step Failure
        run: echo "Failure"
        if: failure()