name: On pull request main closed
on: 
  pull_request:
    branches: 
      - main
      - dev
    types: [closed]

env:
  STATE: ${{github.base_ref == 'main' && 'production' || 'staging' }}
  FIREBASE_PROJECT_ID: chatapptest-edd0d
  FIREBASE_TARGET: ${{github.base_ref == 'main' && 'kslplus-development' || 'kslmessaging-staging' }} 
  FIREBASE_CHANNEL_ID: live

jobs:
  # environment:
  #   runs-on: [self-hosted]
  #   steps:
  #     - name: Stage
  #       run: echo "${{ env.STATE }}"
  #     - name: Github Env
  #       run: echo "${{ toJSON(github) }}"
  #     - name: Event Env
  #       run: echo "${{ toJSON(github.event) }}"
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout from github
        uses: actions/checkout@v3
      - name: Setup Node 14
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install Package and Test
        run: npm ci && npm run test
        env:
          CI: true
      - name: Build Application to artifact
        run: npm run build
        env:
          REACT_APP_STAGE: ${{ env.STATE }}
      - name: Upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-artiface
          path: |
            build
            .firebaserc
            firebase.json

  deploy_hosting:
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Load build artifact
        uses: actions/download-artifact@v3
        with:
          name: application-artiface
      - name: Deploy firebase hosting
        id: firebase_hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ${{env.FIREBASE_PROJECT_ID}}
          channelId: ${{env.FIREBASE_CHANNEL_ID}}
          target: ${{env.FIREBASE_TARGET}}
      - name: Preview URL
        run: echo "${{steps.firebase_hosting.outputs.details_url}}"

  create_tag:
    if: github.base_ref == 'main'
    runs-on: [self-hosted]
    steps:
      - name: Checkout from github
        uses: actions/checkout@v3
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Output Tag Version
        run: |
          echo "${{ toJSON(steps.tag_version.outputs) }}"
        
