name: Approved Pull Request
on:
  pull_request_review:
    branches: 
      - main
      - dev
    types: [submitted]

env:
  FIREBASE_PROJECT_ID: chatapptest-edd0d
  STATE: ${{github.ref_name == 'main' && 'production' || 'staging' }}

jobs:
  print_env:
    runs-on: [self-hosted]
    steps:
      - name: 'Github Env'
        id: inputs
        env:
          ENV_BRANCH: ${{github.ref}}
          ENV_BRANCH_NAME: ${{github.ref_name}}
          ENV_VALUE: ${{ toJSON(github) }}
        run: |
          echo 'branch name: ${{env.ENV_BRANCH_NAME}}'
          echo 'branch: ${{env.ENV_BRANCH}}'
          echo '${{env.ENV_VALUE}}'
  build:
    runs-on: [self-hosted]
    steps:
      - uses: ./.github/workflows/build-deploy.yml
        with:
          state: ${{ env.STATE }}
  deploy_hosting:
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Load build artifact
        uses: actions/download-artifact@v3
        with:
          name: application-artiface
      - name: Deploy firebase hosting
        id: firebase_hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ${{env.FIREBASE_PROJECT_ID}}
          target: ${{env.FIREBASE_TARGET}}
      - name: Preview URL
        run: echo "${{steps.firebase_hosting.outputs.details_url}}"
  
  