name: On pull request main closed
on: 
  pull_request:
    branches: [main]
    types: [closed]
env:
  EVENT_ENV: ${{ toJSON(github) }}
jobs:
  print_event_env:
    runs-on: [self-hosted]
    steps:
      - run: echo '${{ env.EVENT_ENV }}'
      - run: echo '${{ toJSON(github.event.pull_request) }}'
  rebase_dev:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
          fetch-depth: 0
      - name: Rebase dev branch
        uses: sarawuth-pimsai/frontend/.github/actions/merge_hotfix
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      