name: On pull request main
on: 
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  STATE: ${{github.base_ref == 'main' && 'production' || 'staging' }}
  FIREBASE_PROJECT_ID: ${{github.base_ref == 'main' && 'chatapptest-edd0d' || 'chatapptest-edd0d' }} 
  FIREBASE_TARGET: ${{github.base_ref == 'main' && 'kslplus-development' || 'kslmessaging-staging' }} 
  FIREBASE_CHANNEL_ID: PR-${{ github.event.number }}-DEVELOPMENT
  FIREBASE_EXPIRES: 14d

jobs:
  # environment:
  #   runs-on: [self-hosted]
  #   steps:
  #     - name: Stage
  #       run: echo "${{ env.STATE }}"
  #     - name: Github Env
  #       run: echo "${{ toJSON(github) }}"
  #     - name: Event Env
  #       run: echo "${{ toJSON(github.event) }}"
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout from github
        uses: actions/checkout@v3
      - name: Setup Node 14
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install Package
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        env:
          CI: true
        run: npm ci
      - name: Test Application
        run: npm run test
        env:
          CI: true
      - name: Build Application to artifact
        run: npm run build
        env:
          REACT_APP_STAGE: ${{ env.STATE }}
      - name: Upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-artiface
          path: |
            build
            .firebaserc
            firebase.json
            
  deploy_preview_channels:
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Load build artifact
        uses: actions/download-artifact@v3
        with:
          name: application-artiface
      - name: Deploy firebase on PR
        id: firebase_preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: ${{env.FIREBASE_EXPIRES}}
          projectId: ${{env.FIREBASE_PROJECT_ID}}
          channelId: ${{env.FIREBASE_CHANNEL_ID}}
          target: ${{env.FIREBASE_TARGET}}
      - name: Preview URL
        run: echo "${{steps.firebase_preview.outputs.details_url}}"

