name: Pull Request
on:
  pull_request:
    branches:
      - main
env:
  PR_NUMBER: ${{github.event.number}}
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.head.ref}}
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packet
        run: npm ci
      - name: Run test
        run: npm test
        env:
          CI: true
      # - name: Generate build staging
      #   run: npm run build
      #   env:
      #     REACT_APP_STAGE: staging
      - name: Generate build staging
        run: npm run build
        env:
          REACT_APP_STAGE: staging
      - name: Share artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build-path
          path: |
            build
            .firebaserc
            firebase.json
  deploy_pr:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Load build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build-path
      - name: PR Number
        run: echo "$PR_NUMBER => ${{github.event.number}}"
      # - name: PR Number
      #   run: echo $PR_NUMBER ${{github.event.number}}
      # - name: Deploy firebase
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: "${{ secrets.GITHUB_TOKEN }}"
      #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
      #     expires: 14d
      #     projectId: chatapptest-edd0d
      #     channelId: pr_$PR_NUMBER
      #     target: kslplus-develop
      #     #     entryPoint: firebase.json
      #   id: deploy
      # - run: echo ${{steps.deploy.outputs.details_url}}
