name: Pull Request
on:
  pull_request:
    branches:
      - main
env:
  PR_NUMBER: ${{github.event.number}}
jobs:
  build_and_test:
    uses: ./.github/workflows/build_test.yml
    with:
      state: production

  deploy_pr:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Load build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build-path
      - name: PR Number
        run: echo "$PR_NUMBER => ${{github.event.number}}"
      - name: PR Number
        run: echo $PR_NUMBER ${{github.event.number}}
      - name: Deploy firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 14d
          projectId: chatapptest-edd0d
          channelId: PR-${{env.PR_NUMBER}}
          target: kslplus-develop
          #     entryPoint: firebase.json
        id: deploy
      - run: echo ${{steps.deploy.outputs.details_url}}
