name: Pull Request
on:
  pull_request:
    branches:
      - mains
env:
  FIREBASE_PROJECT_ID: chatapptest-edd0d
  FIREBASE_TARGET: kslplus-development
  FIREBASE_CHANNEL_ID: PR-${{ github.event.number }}-DEVELOPMENT
  FIREBASE_EXPIRES: 14d
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build_and_test:
    uses: ./.github/workflows/build_test.yml
    with:
      state: staging

  deploy_preview_channels:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Load build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build-path
      - name: Deploy firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: ${{env.FIREBASE_EXPIRES}}
          projectId: ${{env.FIREBASE_PROJECT_ID}}
          channelId: ${{env.FIREBASE_CHANNEL_ID}}
          target: ${{env.FIREBASE_TARGET}}
