name: Test application
on: [push]
jobs:
  test_script:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Gtihub
        uses: actions/checkout@v3
      - name: Call local action
        uses: ./.github/workflows/call