name: deploy

on: workflow_dispatch

env:
  # kslplus, kslplusstaging
  PROJECT_ID: ${{ github.ref == 'refs/heads/main' && 'chatapptest-edd0d' || 'kslplus-development' }}

jobs:
  build_and_deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3