name: Test application
on: [push]
jobs:
  test_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gtihub
        uses: actions/checkout@v3
      - name: Show files
        run: ls -l ./.github/workflows
      - name: Call local action
        uses: ./.github/workflows/call.yml