name: deploy

on: workflow_dispatch

env:
  # kslplus, kslplusstaging
  PROJECT_ID: ${{ github.ref == 'refs/heads/main' && 'chatapptest-edd0d' || 'kslplus-development' }}

jobs:
  build_and_deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: npm ci && npm run build
      - run: echo "${{ env.PROJECT_ID }}"
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ env.PROJECT_ID }}'