name: Test application
on:
  workflow_dispatch:
    inputs:
      state:
        required: true
        type: choice
        description: State
        options:
        - development
        - production
jobs:
  test:
    steps:
      - name: Checkout Gtihub
        uses: actions/checkout@v3
      - name: Test Script Default
        uses: ./.github/actions/test
        with:
          token: ${{secrets.GITHUB_TOKEN}}