name: Test application
on: [push]
jobs:
  reusable_workflow_job:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Gtihub
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0
      - name: Show files
        run: ls -l ./.github/workflows
      - name: Call local action
        id: test
        uses: ./.github/actions/test
      - name: Result
        env: {OUTPUT: "${{ toJSON(steps.test.outputs) }}"}
        run: "echo $OUTPUT"
      - name: Run local actions
        uses: sarawuth-pimsai/frontend/.github/workflows/call.yml@main